### ISSUE TITLE
ign-cmake online documentation empty

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-cmake#26]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/26)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
See the documentation here:

https://ignitionrobotics.org/libs/cmake

And how on the main page it says "unreleased":

https://ignitionrobotics.org/home

**Comment by j-rivero** [comment]
fixed

**Comment by chapulina** [comment]
I still see "unreleased" and when I click on the Versions tab there aren't any:

![image](https://user-images.githubusercontent.com/5751272/96391402-6b0c2e80-116d-11eb-8a45-b37ae745e6fc.png)

Is your fix deployed yet?

**Comment by j-rivero** [comment]
Uh, I was reviewing issues and acceded to https://ignitionrobotics.org/libs/cmake and looked to me like the problems was fixed. Reopening.

**Comment by azeey** [comment]
This appears fixed now.
